### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by remkolems**
Various outdated packages are updated to reflect the security scan results of Trivy. 

The Dockerfile.deb has also been updated (compiles correctly to a Docker image) to reduce the number of RUN commands and to better handle exceptions. The base image was changed to a slim variant of Debian.

### CODE REVIEW

**Comment by taylorwalton** [comment]
Hey @remkolems thanks for the recommendations! By any chance have you built a new container based off of the new dockerfile? if not ill grab and run myself later this week 👍

**Comment by remkolems** [comment]
Hi Taylor, 

Yes, I've made a new container within my development environment. 1,99GB (new) versus 2,34GB.

Tomorrow I'm going to test further and indepth validate the new container image alongside your YT video instructions.

Did you perhaps test/have used an Alpine base image before for Copilot?

**Comment by taylorwalton** [comment]
Awesome thanks man. Had on my todo list to lighten then image, just went with a base deb 11 cause thats what originally worked ha...but i agree, we need to slim down...let me know how your tests go and how i can help

**Comment by remkolems** [comment]
> Awesome thanks man. Had on my todo list to lighten then image, just went with a base deb 11 cause thats what originally worked ha...but i agree, we need to slim down...let me know how your tests go and how i can help

You're more than welcome, studying to become a DevSecOps engineer. 

I can reduce the container size considerably given the current Dockerfile. On top of that I want to use [https://slimtoolkit.org](https://slimtoolkit.org). At the moment this toolkit is not compatible with my currently installed and latest Docker engine v25.0.2. [Security issues](https://thenewstack.io/leaky-vessels-vulnerability-sinks-container-security/) where found with the open source `runc` container runtime engine.

I already saw the `COPY . .` command yesterday - not yet deep into the intricacies of your source code (Python, VUE, Typescript) - but this exact copy command copies the complete git source code into the container. That is a bit to much.

So the question is: what is the bare minimum that exactly is required for the dir `/opt/copilot`?

**Comment by remkolems** [comment]
Hi Taylor,

Whatever I do, I keep getting the following error message with any of my alterations of the `Dockerfile`, `.dockerignore` and `requirements.txt`. I see libmagic being installed, but to no avail...

Proposal: remove/deny this complete pull request until further notice.

```
[0] Traceback (most recent call last):
[0]   File "/opt/copilot/backend/copilot.py", line 23, in <module>
[0]     from app.routers import agents
[0]   File "/opt/copilot/backend/app/routers/__init__.py", line 3, in <module>
[0]     from .connectors import router as connectors_router
[0]   File "/opt/copilot/backend/app/routers/connectors.py", line 3, in <module>
[0]     from app.connectors.routes import connector_router
[0]   File "/opt/copilot/backend/app/connectors/routes.py", line 19, in <module>
[0]     from app.connectors.services import ConnectorServices
[0]   File "/opt/copilot/backend/app/connectors/services.py", line 16, in <module>
[0]     from app.connectors.cortex.utils.universal import verify_cortex_connection
[0]   File "/opt/copilot/backend/app/connectors/cortex/utils/universal.py", line 5, in <module>
[0]     from cortex4py.api import Api
[0]   File "/opt/venv/lib/python3.11/site-packages/cortex4py/api.py", line 9, in <module>
[0]     from .controllers.organizations import OrganizationsController
[0]   File "/opt/venv/lib/python3.11/site-packages/cortex4py/controllers/__init__.py", line 6, in <module>
[0]     from .analyzers import AnalyzersController
[0]   File "/opt/venv/lib/python3.11/site-packages/cortex4py/controllers/analyzers.py", line 3, in <module>
[0]     import magic
[0]   File "/opt/venv/lib/python3.11/site-packages/magic/__init__.py", line 209, in <module>
[0]     libmagic = loader.load_lib()
[0]                ^^^^^^^^^^^^^^^^^
[0]   File "/opt/venv/lib/python3.11/site-packages/magic/loader.py", line 49, in load_lib
[0]     raise ImportError('failed to find libmagic.  Check your installation')
[0] ImportError: failed to find libmagic.  Check your installation
[0] npm run start-server exited with code 1
```

**Comment by taylorwalton** [comment]
hmm ill see if i can find some time to look at this over the weekend as well...thanks!

**Pull request closed without merging**
